[View in Colaboratory](https://colab.research.google.com/github/jonaskratochvil/hello-world/blob/master/Moje_konecne_funkcni_NN2.ipynb)

In [0]:
import numpy as np

import random 

from scipy.stats import truncnorm

In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

def stable_softmax(x):
  exps = np.exp(X - np.max(X))
  return exps / np.sum(exps)     

    cross_entropy_loss = -(1.0/intput_data.T.shape[0]) * np.sum(input_labels*np.log(l1) + (1-input_labels)*np.log(1-l1))


In [0]:
def truncated_normal(mean=0, sd=1, low=0, upp=10):
    return truncnorm((low - mean) / sd, (upp - mean) / sd, loc=mean, scale=sd)

In [0]:
class NeuralNetwork:
  
  def __init__(self, n_in_nodes, n_hidden_nodes, n_out_nodes, learning_rate):
    
    self.n_in_nodes = n_in_nodes
    self.hidden_nodes = n_hidden_nodes
    self.n_out_nodes = n_out_nodes
    self.learning_rate = learning_rate
    self.weights_in = np.random.randn(n_hidden_nodes, n_in_nodes)
    self.weights_out = np.random.randn(n_out_nodes, n_hidden_nodes)
    self.bias_in = np.random.randn(n_hidden_nodes,1)
    self.bias_out = np.random.randn(n_out_nodes,1)
  
  def train(self, input_data, input_labels):
    
    # Transponovani dat z 4x3 na 3x4 -> weights jsou 4x3, 1x4
    
    input_data = np.array(input_data, ndmin = 2).T
    input_labels = np.array(input_labels, ndmin = 2).T
    
    # Forward propagate 4x3 x 3x4 -> 4x4 
    
    l0 = sigmoid(np.dot(self.weights_in, input_data)+self.bias_in)
    
    # 1x4 x 4x4 -> 1x4
    
    l1 = sigmoid(np.dot(self.weights_out, l0)+self.bias_out)
    
    self.output_error = l1 - input_labels # dal jsem derivaci square loss kdyz napr 0.8 - 0 -> zaporny learning rate da to znamenko tak jak chci
    
    # kdyz 0.1 - 1 tak zase ten learning rate to hodi tam kam chci
    
    # Backpropagate -> deltas in first and zero layer from Nielsen formula
    
    d1 = self.output_error*(l1*(1-l1))
    d0 = np.dot(self.weights_out.T,d1)*(l0*(1-l0))
    
    # Weight update change from Nielsen formula to np.dot(delta1, output0.T)
    
    self.dw_out = np.dot(d1,l0.T)
    self.dw_in = np.dot(d0,input_data.T)
    
    self.db_out = d1
    self.db_in = d0
    
  def SGD(self, X, y, epochs, batch_size):
    
    batch_w_in_update = []
    batch_w_out_update = []
    batch_b_in_update = []
    batch_b_out_update = []
    
    for epoch in range(epochs):
      
      # shuffle randomly data before start of each epoch
      
      data_shuffle = [i for i in range(X.shape[0])]
      data_shuffle = random.sample(data_shuffle, len(data_shuffle))

      X = np.array([X[i] for i in data_shuffle])
      y = np.array([y[i] for i in data_shuffle])
            
      for minibatch in range(0,X.shape[0],batch_size):
        
        for example in range(minibatch,minibatch+batch_size):
          
          # Append weight and biases gradients
          
          self.train(X[example],y[example])
          batch_w_in_update.append(self.dw_in)
          batch_w_out_update.append(self.dw_out)
          batch_b_in_update.append(self.db_in)
          batch_b_out_update.append(self.db_out)
          
          minibatch = minibatch
        
        # Update current weights to new ones with minibatch update
        
        self.weights_in = self.weights_in - self.learning_rate/batch_size * np.sum(batch_w_in_update[minibatch:minibatch+batch_size]) 
        self.weights_out = self.weights_out - self.learning_rate/batch_size * np.sum(batch_w_out_update[minibatch:minibatch+batch_size])
        
        self.bias_in = self.bias_in - self.learning_rate/batch_size * np.sum(batch_b_in_update[minibatch:minibatch+batch_size]) 
        self.bias_out = self.bias_out - self.learning_rate/batch_size * np.sum(batch_b_out_update[minibatch:minibatch+batch_size])
        
      if (epoch % 50000) == 0:

        print ("epoch:" + str(epoch) + " error: " + str(np.mean(np.abs(self.output_error))))
    
  def run(self, test_data):
     
    test_data = np.array(test_data, ndmin = 2).T
    l0 = sigmoid(np.dot(self.weights_in, test_data) + self.bias_in)
    l1 = sigmoid(np.dot(self.weights_out, l0) + self.bias_out)
    
    return l1
    
    
    

In [0]:
net10 = NeuralNetwork(3, 10, 1, 0.0001)

In [0]:
X = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1],])

y = np.array([[0,0,1,1]]).T


In [201]:
net10.SGD(X,y,200000,2)

epoch:0 error: 0.9290398094329656
epoch:100000 error: 0.9993385317329402


In [205]:
print(net.weights_out)

print(net.weights_in)

[[-11.73027663 -12.59629059 -12.88765392 -11.9258149 ]]
[[ 0.85564238 -2.94344901  0.64150495]
 [-1.2823215  -0.65962992  0.69009751]
 [-1.72811664 -2.24624863 -1.50542336]
 [-0.27508352  0.194147   -1.18839612]]


In [204]:
point = np.array([[0,1,1]]) 

net.run(point)

array([[6.31621396e-06]])

In [0]:
for i in range(100000):
  net.train(X,y)
  if (i % 10000) == 0:

      print ("iteration:" + str(i) + " accuracy: " + str(1 - np.mean(np.abs(net.output_error))))

In [148]:
v = ["bear", "lion", "dog"]

z = []

for i in v:
  z.append(i)
  

ind_list = [i for i in range(len(z))]

ind_list = random.sample(ind_list, len(ind_list))

z = [z[i] for i in ind_list]

print(z)




['lion', 'dog', 'bear']


In [152]:
X = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1],])

y = np.array([[0,0,1,1]]).T

data_shuffle = [i for i in range(X.shape[0])]
data_shuffle = random.sample(data_shuffle, len(data_shuffle))

X = np.array([X[i] for i in data_shuffle])
y = np.array([y[i] for i in data_shuffle])

print(X)
print(y)


[[0 1 1]
 [1 1 1]
 [0 0 1]
 [1 0 1]]
[[0]
 [1]
 [0]
 [1]]


In [0]:
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST.data/", one_hot = True)

In [5]:
print(mnist.train.labels.shape)

(55000, 10)


In [0]:
net_mnist = NeuralNetwork(784, 10 , 10, 0.1)

In [0]:
for i in range(1000):
  net_mnist.train(mnist.train.images,mnist.train.labels)
  
  if i % 100 == 0:
    
    print ("iteration:" + str(i) + " accuracy: " + str(1 - np.mean(np.abs(net_mnist.output_error))))

In [10]:
print(mnist.test.labels[0])

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


In [0]:
net_mnist.run(mnist.test.images[0])